In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np

from sklearn.datasets import load_digits

digits = load_digits()

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, train_size=0.7)

In [40]:
lr = LogisticRegression(solver = 'newton-cg', multi_class='auto')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9777777777777777

In [41]:
sv = SVC()
sv.fit(X_train, y_train)
sv.score(X_test, y_test)

0.9888888888888889

In [42]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [43]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [44]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [46]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [47]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], \
                                    digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(solver = 'newton-cg', multi_class='auto'), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    

In [48]:
score_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [49]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [50]:
score_rf

[0.9365609348914858, 0.9632721202003339, 0.9181969949916527]

In [51]:
from sklearn.model_selection import cross_val_score

In [52]:
cross_val_score(LogisticRegression(solver = 'newton-cg', multi_class='auto'), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [53]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target)

array([0.93333333, 0.90555556, 0.95821727, 0.96657382, 0.9275766 ])